### ISSUE TITLE
HTTP server crashes on visiting https://<IP-ADDRESS>:8080/sb_head.html

### ISSUE THREAD

**Issue by rnitin** [yashas-salankimatt/sb_web#1]
Hi,
My HTTP server crashes when I visit the sb_head.html page.

It shows the following error message: 

>  [Wed Feb 08 2023 19:46:01 GMT-0600 (Central Standard Time)]  "GET /sb_head.html" "Mozilla/5.0 (Android 12; Mobile; rv:108.0) Gecko/108.0 Firefox/108.0"
> _http_outgoing.js:470
>     throw new ERR_HTTP_HEADERS_SENT('set');
>     ^
> 
> Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
>     at ServerResponse.setHeader (_http_outgoing.js:470:11)
>     at module.exports.ResponseStream.(anonymous function) [as setHeader] (/usr/local/lib/node_modules/http-server/node_modules/union/lib/response-stream.js:100:34)
>     at Object.exports.(anonymous function) (/usr/local/lib/node_modules/http-server/lib/core/status-handlers.js:57:7)
>     at Readable.stream.on (/usr/local/lib/node_modules/http-server/lib/core/index.js:339:22)
>     at Readable.emit (events.js:198:13)
>     at emitErrorNT (internal/streams/destroy.js:91:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
>     at process._tickCallback (internal/process/next_tick.js:63:19)

However, I face no issues until I visit the AutobahnPython screen.

**Comment by yashas-salankimatt** [comment]
Hi, can you contact me at yashas.salankimatt@gmail.com so that we can set up a time for me to look at this error?

**Comment by rnitin** [comment]
Hi, as suggested by a student in class, a fix is to try and update the version of `node` installed in the computer.
Updating from `10` to `18` solved my issue.
